### ISSUE TITLE
How to use Plan Variables?

### ISSUE THREAD

**Issue by blundell** [JetBrains/jetbrains-gradle-plugins#13]
In the example project b, the build.gradle.kts has:

```
    planVariables = mapOf("example" to "ciao")
```

However I can't see this being used in the [project-b-1.tf](https://github.com/JetBrains/jetbrains-gradle-plugins/blob/master/examples/terraform/project-b/src/main/terraform/project-b-1.tf). Is it supposed to be?

So the simpler question is, how do I use planVariables once I declare them? :-)

**Comment by blundell** [comment]
I understand now that these are used as the default value for variables you declare in your `*.tf` files. 
Perhaps the example should include something to make that obvious like:

build.gradle.kts:

planVariables = mapOf("myExampleVar" to "ciao")

Main.tf:

 `variable "myExampleVar" {}`

**Comment by lamba92** [comment]
Indeed, the variables are passed using [command line](https://www.terraform.io/cli/commands/plan#input-variables-on-the-command-line). I will update the examples.
