### ISSUE TITLE
State file is not being created

### ISSUE THREAD

**Issue by blundell** [JetBrains/jetbrains-gradle-plugins#14]
I ran `terraformApply` and I got a .lock.hcl file, but I did not get a state file? Should I have?

Also is this an error in the readme: 
![image](https://user-images.githubusercontent.com/655860/153078122-57c27f61-e22d-42e1-ae8f-c64c75c8222a.png)

Under the state file title it says:

> The location of the lock file can be modified in the source set:

and the example says  `lockFile = ` .. should it be `stateFile =`?

**Comment by blundell** [comment]
Ah I have found a state file in my original root project.

i.e. I am running in a module in a composite project

```
/my-project/                              <<< 1 state file was found here
   /my-composite-build/           <<< 3 here would also be ok, its the root project I expect 
       /my-terraform-module/    <<< 2 was hoping for it here
```

**Comment by lamba92** [comment]
The [lock file](https://www.terraform.io/language/files/dependency-lock) is a dependency management mechanism to avoid installing unwanted upgrades during `terraform init`. On the other hand the plan file has it's own `stateFile` variable with a default in `"src/$name/terraform/terraform.tfstate"`.

**Comment by blundell** [comment]
Any thoughts on this? I'm stuck without a state file :-)

I can see the state is generated in build/terraform/main/runtimeExecution/terraform.tfstate

I guess a work around for now is if I copy that file back out the build folder manually after each apply?

**Comment by blundell** [comment]
💯
