### ISSUE TITLE
terraformPlan fails every other time (with single lambda resource)

### ISSUE THREAD

**Issue by blundell** [JetBrains/jetbrains-gradle-plugins#15]
I'm using the lambda integration from the README, it creates a resource and its the only resource in the whole project.

```
> Task :my-root-project:my-terraform-project:terraformMainPlan FAILED
╷ IDLE
│ Error: Reference to undeclared input variable
│ 
│   on project-rbc.tf line 98, in resource "aws_lambda_function" "my_lambda":
│   98:   filename = "${var.resources.myLambda_jar.path}"
│ 
│ An input variable with the name "resources" has not been declared. This
│ variable can be declared with a variable "resources" {} block.
╵

FAILURE: Build failed with an exception.
```

I get this failure every 1st build, then I run the same command again (`terraformPlan`) and it succeeds. 
Might be something to do with the ordering of when the resources are created vs when my `tf` file is accessed?

Also in the IDE, the line itself is always declared as an "unresolved" reference.

**Comment by lamba92** [comment]
Will have a look

**Comment by lamba92** [comment]
could you share a repro project?

**Comment by blundell** [comment]
Created a simple reproduction project https://github.com/blundell/TerraformGradlePluginPlayground/tree/lambda_not_found_repro/backend however it no longer fails every other time (it succeeds every time). But the IDE still shows it as red/missing:

![image](https://user-images.githubusercontent.com/655860/155030949-8fcfcd92-4b24-4330-8799-e6ca787c58cc.png)

**Comment by lamba92** [comment]
Indeed the TF IJ plugin does not support yet this setup. I will try to support it as soon as I can.
