### ISSUE TITLE
Liquibase | UpdateSql file output

### ISSUE THREAD

**Issue by crorodriguezro** [JetBrains/jetbrains-gradle-plugins#2]
Hi!
I'm trying to write the output of updateSql to a file. But the file is not being generated.
My config looks like this:

liquibase {
    activities {
        all {
            arguments["changeLogFile"] = "src/main/resources/db/dbchangelog-master.yaml"
            arguments["outputFile"] = "script.sql"
        }

        register("local") {
            arguments["url"] = "jdbc:sqlserver://localhost:1433"
            arguments["username"] = ""
            arguments["password"] = ""
            arguments["outputFile"] = "script.sql"
        }
    }
}

Do you know what is the correct config? 
Thanks in advance

**Comment by lamba92** [comment]
I'll close it. Let me know if you need further help.
