### ISSUE TITLE
How to debug: Error: "xxxx": required field is not set

### ISSUE THREAD

**Issue by farrukhnajmi** [JetBrains/jetbrains-gradle-plugins#6]
I am new to terraform and this plugin. 

When I execute the terraformMainPlan task I get the following errors. I am unsure how to debug the errors and fix them. TIA for any guidance.

```
> Task :terraform:terraformExtract UP-TO-DATE
> Task :terraform:copyMainMetadataFiles NO-SOURCE
> Task :terraform:terraformMainMetadata UP-TO-DATE
> Task :terraform:generateMainExecutionContext UP-TO-DATE
> Task :terraform:generateMainResFile UP-TO-DATE
> Task :terraform:copyMainResFileInExecutionContext

> Task :terraform:terraformMainInit FAILED
Initializing modules...

Initializing the backend...

> Task :terraform:syncMainLockFile UP-TO-DATE
7 actionable tasks: 2 executed, 5 up-to-date
╷
│ Error: "region": required field is not set
│ 
│ 
╵

╷
│ Error: "bucket": required field is not set
│ 
│ 
╵

╷
│ Error: "key": required field is not set
│ 
│ 
╵
```

**Comment by lamba92** [comment]
Hello! I believe there are some issues in your provider configuration in you TF sources. Can you share the project?

Also which version of the plugin are you using?

**Comment by farrukhnajmi** [comment]
Thank you! I have determined the cause of my problem to be a backend using S3 provider which was missing some required arguments. The broader question I have is not specific to my project but how best to determine which line in which file or at least which type of block has the issue. Anything that would help me find the source of the mis-configuration.

**Comment by lamba92** [comment]
The plugin should output the terraform errors 1 to 1. The error message you attached in the first message is from Terraform itself, but indeed it seems lacking some details like the lines where the error is. 

I am not sure if it's the plugin fault or IntelliJ fault (if you are using IJ, the error output logs are often manipulated and some lines but have been swallowed). 

Can you reproduce the error using just the command line and paste the output?

**Comment by farrukhnajmi** [comment]
Hi @lamba92 , The terraform command line gives same error lacking details on where to look. So it seems like a terraform limitation.

I am closing this issue.
